name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - v19

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:
       branches:
        - v19
  
  schedule:
    - cron: "0 2 * * *"  

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: scjtqs/nextcloud:adm64

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker-compose --file docker-compose.test.yml build
            docker-compose --file docker-compose.test.yml run sut
          else
            docker build . --file Dockerfile
          fi

#  # Push image to GitHub Packages.
#  # See also https://docs.docker.com/docker-hub/builds/
#  push0:
#    # Ensure test job passes before pushing image.
#    needs: test
#
#    runs-on: ubuntu-latest
#    #    if: github.event_name == 'push'
#
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Build image
#        run: docker build . --file Dockerfile --tag $IMAGE_NAME
#
#      - name: Log into registry
#        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login  -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
#
#      - name: Push image
#        run: docker push $IMAGE_NAME


  push1:
    # Ensure test job passes before pushing image.
    needs: test

    runs-on: ubuntu-latest
#    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login  -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Log into aliyun
        run: echo "${{ secrets.DOCKER_PASSWORD2 }}" | docker login  -u ${{ secrets.DOCKER_USERNAME2 }} --password-stdin registry.cn-hangzhou.aliyuncs.com

      - name: buildx
        run: ./build_multi.sh

  push2:
    # Ensure test job passes before pushing image.
    needs: test

    runs-on: ubuntu-latest
    #    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login  -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Log into aliyun
        run: echo "${{ secrets.DOCKER_PASSWORD2 }}" | docker login  -u ${{ secrets.DOCKER_USERNAME2 }} --password-stdin registry.cn-hangzhou.aliyuncs.com

      - name: buildx-alpine
        run: ./build_multi_alpine.sh
  push3:
    # Ensure test job passes before pushing image.
    needs: test

    runs-on: ubuntu-latest
    #    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login  -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Log into aliyun
        run: echo "${{ secrets.DOCKER_PASSWORD2 }}" | docker login  -u ${{ secrets.DOCKER_USERNAME2 }} --password-stdin registry.cn-hangzhou.aliyuncs.com

      - name: buildx-alpine-nginx
        run: ./build_multi_alpine_nginx.sh
